// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: vizierapi.proto

package vizierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VizierService_HealthCheck_FullMethodName = "/px.api.vizierpb.VizierService/HealthCheck"
)

// VizierServiceClient is the client API for VizierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The API that manages all communication with a particular Vizier cluster.
type VizierServiceClient interface {
	// Start a stream to receive health updates from the Vizier service.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthCheckResponse], error)
}

type vizierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVizierServiceClient(cc grpc.ClientConnInterface) VizierServiceClient {
	return &vizierServiceClient{cc}
}

func (c *vizierServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthCheckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VizierService_ServiceDesc.Streams[0], VizierService_HealthCheck_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthCheckRequest, HealthCheckResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VizierService_HealthCheckClient = grpc.ServerStreamingClient[HealthCheckResponse]

// VizierServiceServer is the server API for VizierService service.
// All implementations must embed UnimplementedVizierServiceServer
// for forward compatibility.
//
// The API that manages all communication with a particular Vizier cluster.
type VizierServiceServer interface {
	// Start a stream to receive health updates from the Vizier service.
	HealthCheck(*HealthCheckRequest, grpc.ServerStreamingServer[HealthCheckResponse]) error
	mustEmbedUnimplementedVizierServiceServer()
}

// UnimplementedVizierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVizierServiceServer struct{}

func (UnimplementedVizierServiceServer) HealthCheck(*HealthCheckRequest, grpc.ServerStreamingServer[HealthCheckResponse]) error {
	return status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVizierServiceServer) mustEmbedUnimplementedVizierServiceServer() {}
func (UnimplementedVizierServiceServer) testEmbeddedByValue()                       {}

// UnsafeVizierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VizierServiceServer will
// result in compilation errors.
type UnsafeVizierServiceServer interface {
	mustEmbedUnimplementedVizierServiceServer()
}

func RegisterVizierServiceServer(s grpc.ServiceRegistrar, srv VizierServiceServer) {
	// If the following call pancis, it indicates UnimplementedVizierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VizierService_ServiceDesc, srv)
}

func _VizierService_HealthCheck_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VizierServiceServer).HealthCheck(m, &grpc.GenericServerStream[HealthCheckRequest, HealthCheckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VizierService_HealthCheckServer = grpc.ServerStreamingServer[HealthCheckResponse]

// VizierService_ServiceDesc is the grpc.ServiceDesc for VizierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VizierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "px.api.vizierpb.VizierService",
	HandlerType: (*VizierServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HealthCheck",
			Handler:       _VizierService_HealthCheck_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vizierapi.proto",
}
