// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: vizierapi.proto

package vizierpb

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status codes enum
type Code int32

const (
	Code_OK                  Code = 0
	Code_INTERNAL            Code = 1
	Code_INVALID_ARGUMENT    Code = 2
	Code_NOT_FOUND           Code = 3
	Code_PERMISSION_DENIED   Code = 4
	Code_UNIMPLEMENTED       Code = 5
	Code_FAILED_PRECONDITION Code = 6
	Code_RESOURCE_EXHAUSTED  Code = 7
	Code_CANCELLED           Code = 8
	Code_UNKNOWN             Code = 9
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
		1: "INTERNAL",
		2: "INVALID_ARGUMENT",
		3: "NOT_FOUND",
		4: "PERMISSION_DENIED",
		5: "UNIMPLEMENTED",
		6: "FAILED_PRECONDITION",
		7: "RESOURCE_EXHAUSTED",
		8: "CANCELLED",
		9: "UNKNOWN",
	}
	Code_value = map[string]int32{
		"OK":                  0,
		"INTERNAL":            1,
		"INVALID_ARGUMENT":    2,
		"NOT_FOUND":           3,
		"PERMISSION_DENIED":   4,
		"UNIMPLEMENTED":       5,
		"FAILED_PRECONDITION": 6,
		"RESOURCE_EXHAUSTED":  7,
		"CANCELLED":           8,
		"UNKNOWN":             9,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_vizierapi_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_vizierapi_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_vizierapi_proto_rawDescGZIP(), []int{0}
}

// Status message
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       Code                   `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=px.api.vizierpb.Code" json:"err_code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Context       *any1.Any              `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_vizierapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_vizierapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_vizierapi_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetErrCode() Code {
	if x != nil {
		return x.ErrCode
	}
	return Code_OK
}

func (x *Status) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Status) GetContext() *any1.Any {
	if x != nil {
		return x.Context
	}
	return nil
}

// Request for the HealthCheck call.
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the cluster encoded as a string with dashes.
	ClusterId     string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_vizierapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vizierapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_vizierapi_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// Response for the HealthCheck call.
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The status of the cluster.
	Status        *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_vizierapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vizierapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_vizierapi_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_vizierapi_proto protoreflect.FileDescriptor

const file_vizierapi_proto_rawDesc = "" +
	"\n" +
	"\x0fvizierapi.proto\x12\x0fpx.api.vizierpb\x1a\x19google/protobuf/any.proto\"|\n" +
	"\x06Status\x120\n" +
	"\berr_code\x18\x01 \x01(\x0e2\x15.px.api.vizierpb.CodeR\aerrCode\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\acontext\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\acontext\"3\n" +
	"\x12HealthCheckRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"F\n" +
	"\x13HealthCheckResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.px.api.vizierpb.StatusR\x06status*\xb8\x01\n" +
	"\x04Code\x12\x06\n" +
	"\x02OK\x10\x00\x12\f\n" +
	"\bINTERNAL\x10\x01\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x03\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x04\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\x05\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\x06\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\a\x12\r\n" +
	"\tCANCELLED\x10\b\x12\v\n" +
	"\aUNKNOWN\x10\t2k\n" +
	"\rVizierService\x12Z\n" +
	"\vHealthCheck\x12#.px.api.vizierpb.HealthCheckRequest\x1a$.px.api.vizierpb.HealthCheckResponse0\x01B8Z6github.com/wrongerror/observo-connector/proto/vizierpbb\x06proto3"

var (
	file_vizierapi_proto_rawDescOnce sync.Once
	file_vizierapi_proto_rawDescData []byte
)

func file_vizierapi_proto_rawDescGZIP() []byte {
	file_vizierapi_proto_rawDescOnce.Do(func() {
		file_vizierapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vizierapi_proto_rawDesc), len(file_vizierapi_proto_rawDesc)))
	})
	return file_vizierapi_proto_rawDescData
}

var file_vizierapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vizierapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vizierapi_proto_goTypes = []any{
	(Code)(0),                   // 0: px.api.vizierpb.Code
	(*Status)(nil),              // 1: px.api.vizierpb.Status
	(*HealthCheckRequest)(nil),  // 2: px.api.vizierpb.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: px.api.vizierpb.HealthCheckResponse
	(*any1.Any)(nil),            // 4: google.protobuf.Any
}
var file_vizierapi_proto_depIdxs = []int32{
	0, // 0: px.api.vizierpb.Status.err_code:type_name -> px.api.vizierpb.Code
	4, // 1: px.api.vizierpb.Status.context:type_name -> google.protobuf.Any
	1, // 2: px.api.vizierpb.HealthCheckResponse.status:type_name -> px.api.vizierpb.Status
	2, // 3: px.api.vizierpb.VizierService.HealthCheck:input_type -> px.api.vizierpb.HealthCheckRequest
	3, // 4: px.api.vizierpb.VizierService.HealthCheck:output_type -> px.api.vizierpb.HealthCheckResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vizierapi_proto_init() }
func file_vizierapi_proto_init() {
	if File_vizierapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vizierapi_proto_rawDesc), len(file_vizierapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vizierapi_proto_goTypes,
		DependencyIndexes: file_vizierapi_proto_depIdxs,
		EnumInfos:         file_vizierapi_proto_enumTypes,
		MessageInfos:      file_vizierapi_proto_msgTypes,
	}.Build()
	File_vizierapi_proto = out.File
	file_vizierapi_proto_goTypes = nil
	file_vizierapi_proto_depIdxs = nil
}
