# Observo Connector Configuration Example

# Vizier connection settings
address: "localhost:50051"
cluster_id: "my-cluster"

# TLS/SSL configuration
disable_ssl: false
skip_verify: false
ca_cert: "certs/ca.crt"
client_cert: "certs/client.crt"
client_key: "certs/client.key"
server_name: "vizier.example.com"
cert_dir: "./certs"

# HTTP Server settings
server_port: 8080

# Logging configuration
log_level: "info"

# Export settings
export:
  default_format: "json"
  compression: false
  batch_size: 1000
