#!/bin/bash
# Quick curl commands for testing Pixie scripts
# Copy and paste these commands individually to test

echo "=== Quick Test Commands for Pixie Scripts ==="
echo ""
echo "1. Start the server first:"
echo "./observo-connector --address localhost:50300 --cluster-id 244a69ca-4b9d-42cc-b7fd-80df82264e72 --jwt-key c7144cb92576c8202aaf40d3dec598cb4155de9a7ac9f830de4dd1566440d10517c83174b2399f4b01ba437c332b616c3e5d52909ce1641fec185d97a81dca96 --jwt-service observo-connector --health-check --skip-verify"
echo ""
echo "2. Test basic health:"
echo "curl \"http://localhost:8080/api/v1/health\""
echo ""
echo "3. Test original scripts:"
echo "curl \"http://localhost:8080/api/v1/metrics?script=http_overview\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=resource_usage\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=network_stats\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=error_analysis\""
echo ""
echo "4. Test new scripts:"
echo "curl \"http://localhost:8080/api/v1/metrics?script=net_flow_graph\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=http_data_tracer\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=http_request_stats\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=http_performance\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=service_dependencies\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=service_performance\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=service_map\""
echo ""
echo "5. List all scripts:"
echo "curl \"http://localhost:8080/api/v1/scripts\""
echo ""
echo "6. Test with parameters:"
echo "curl \"http://localhost:8080/api/v1/metrics?script=http_overview&start_time=-10m&namespace=default\""
echo "curl \"http://localhost:8080/api/v1/metrics?script=service_performance&namespace=default&top_count=20\""
echo ""
echo "Copy and run these commands one by one to test the functionality!"
