// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: proto/vizierapi_simple.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Simple but accurate status - using int32 like Pixie
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_vizierapi_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vizierapi_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_vizierapi_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Minimal but accurate ExecuteScriptRequest
type ExecuteScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryStr      string                 `protobuf:"bytes,1,opt,name=query_str,json=queryStr,proto3" json:"query_str,omitempty"`
	ClusterId     string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // Field 3 like Pixie
	Mutation      bool                   `protobuf:"varint,5,opt,name=mutation,proto3" json:"mutation,omitempty"`                   // Field 5 like Pixie
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScriptRequest) Reset() {
	*x = ExecuteScriptRequest{}
	mi := &file_proto_vizierapi_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScriptRequest) ProtoMessage() {}

func (x *ExecuteScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vizierapi_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScriptRequest.ProtoReflect.Descriptor instead.
func (*ExecuteScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_vizierapi_simple_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteScriptRequest) GetQueryStr() string {
	if x != nil {
		return x.QueryStr
	}
	return ""
}

func (x *ExecuteScriptRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ExecuteScriptRequest) GetMutation() bool {
	if x != nil {
		return x.Mutation
	}
	return false
}

// Minimal but accurate ExecuteScriptResponse
type ExecuteScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	QueryId       string                 `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScriptResponse) Reset() {
	*x = ExecuteScriptResponse{}
	mi := &file_proto_vizierapi_simple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScriptResponse) ProtoMessage() {}

func (x *ExecuteScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vizierapi_simple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScriptResponse.ProtoReflect.Descriptor instead.
func (*ExecuteScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_vizierapi_simple_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteScriptResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExecuteScriptResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_vizierapi_simple_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vizierapi_simple_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_vizierapi_simple_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_vizierapi_simple_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vizierapi_simple_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_vizierapi_simple_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_vizierapi_simple_proto protoreflect.FileDescriptor

const file_proto_vizierapi_simple_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/vizierapi_simple.proto\x12\x0fpx.api.vizierpb\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x14ExecuteScriptRequest\x12\x1b\n" +
	"\tquery_str\x18\x01 \x01(\tR\bqueryStr\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bmutation\x18\x05 \x01(\bR\bmutation\"c\n" +
	"\x15ExecuteScriptResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.px.api.vizierpb.StatusR\x06status\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\tR\aqueryId\"3\n" +
	"\x12HealthCheckRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"F\n" +
	"\x13HealthCheckResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.px.api.vizierpb.StatusR\x06status2\xcd\x01\n" +
	"\rVizierService\x12Z\n" +
	"\vHealthCheck\x12#.px.api.vizierpb.HealthCheckRequest\x1a$.px.api.vizierpb.HealthCheckResponse0\x01\x12`\n" +
	"\rExecuteScript\x12%.px.api.vizierpb.ExecuteScriptRequest\x1a&.px.api.vizierpb.ExecuteScriptResponse0\x01B/Z-github.com/wrongerror/observo-connector/protob\x06proto3"

var (
	file_proto_vizierapi_simple_proto_rawDescOnce sync.Once
	file_proto_vizierapi_simple_proto_rawDescData []byte
)

func file_proto_vizierapi_simple_proto_rawDescGZIP() []byte {
	file_proto_vizierapi_simple_proto_rawDescOnce.Do(func() {
		file_proto_vizierapi_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vizierapi_simple_proto_rawDesc), len(file_proto_vizierapi_simple_proto_rawDesc)))
	})
	return file_proto_vizierapi_simple_proto_rawDescData
}

var file_proto_vizierapi_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_vizierapi_simple_proto_goTypes = []any{
	(*Status)(nil),                // 0: px.api.vizierpb.Status
	(*ExecuteScriptRequest)(nil),  // 1: px.api.vizierpb.ExecuteScriptRequest
	(*ExecuteScriptResponse)(nil), // 2: px.api.vizierpb.ExecuteScriptResponse
	(*HealthCheckRequest)(nil),    // 3: px.api.vizierpb.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 4: px.api.vizierpb.HealthCheckResponse
}
var file_proto_vizierapi_simple_proto_depIdxs = []int32{
	0, // 0: px.api.vizierpb.ExecuteScriptResponse.status:type_name -> px.api.vizierpb.Status
	0, // 1: px.api.vizierpb.HealthCheckResponse.status:type_name -> px.api.vizierpb.Status
	3, // 2: px.api.vizierpb.VizierService.HealthCheck:input_type -> px.api.vizierpb.HealthCheckRequest
	1, // 3: px.api.vizierpb.VizierService.ExecuteScript:input_type -> px.api.vizierpb.ExecuteScriptRequest
	4, // 4: px.api.vizierpb.VizierService.HealthCheck:output_type -> px.api.vizierpb.HealthCheckResponse
	2, // 5: px.api.vizierpb.VizierService.ExecuteScript:output_type -> px.api.vizierpb.ExecuteScriptResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vizierapi_simple_proto_init() }
func file_proto_vizierapi_simple_proto_init() {
	if File_proto_vizierapi_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vizierapi_simple_proto_rawDesc), len(file_proto_vizierapi_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vizierapi_simple_proto_goTypes,
		DependencyIndexes: file_proto_vizierapi_simple_proto_depIdxs,
		MessageInfos:      file_proto_vizierapi_simple_proto_msgTypes,
	}.Build()
	File_proto_vizierapi_simple_proto = out.File
	file_proto_vizierapi_simple_proto_goTypes = nil
	file_proto_vizierapi_simple_proto_depIdxs = nil
}
